version: '3.9'
services:
    db:
        build: .

    post:
        build: ./src
        ports:
            - "5000:5000"
        links:
            - "db"
            - "templates"
    templates:
        build: ./templates