version: "3.9"
services:
    flask:
        build: ./flask_code
        ports:
            - "5000:5000"
        volumes:
            - ./flask_code:/src
        depends_on:
            - redis
    redis:
        image: redis
        ports:
            - "6379:6379"